### ISSUE TITLE
Release patches nightly

### ISSUE THREAD

**Issue by aleclarson** [radashi-org/radashi#300]
During nightly `publish-beta` workflow, skip the beta release if only `fix:` commits exist and publish a patch instead.

**Comment by aleclarson** [comment]
Alternatively, publish patches immediately upon merging. 🤔

**Comment by MarlonPassos-git** [comment]
I like the idea; in the current flow, we’re only handling major and minor releases, so this could be a way to introduce patch releases in between.

However, if we only use the main branch, this could lead to some issues.

Imagine someone adds a new function `xyz`, we merge it into main, which goes to `@beta`. Then, someone opens a PR with a `fix` for this new `xyz` function, addressing a type issue. Although this PR is labeled as a `fix`, it shouldn’t be merged immediately since it’s directly tied to a `feat` PR still in beta.

We could:
- Follow this flow only until there’s a `feat`, then pause.
- Create a `next` branch or something similar to separate the flows (though it could get a bit confusing).
- Simply program the CI to handle these more complex cases.

**Comment by MarlonPassos-git** [comment]
By the way, have you decided on the frequency for minor releases? Will it be monthly, every set period, or after a certain number of new features?

**Comment by aleclarson** [comment]
Here's how I've got it set up now:

1. PRs with new features must edit [next-minor.md](https://github.com/radashi-org/radashi/blob/main/.github/next-minor.md)
2. PRs with breaking changes must edit [next-major.md](https://github.com/radashi-org/radashi/blob/main/.github/next-major.md) and target the `next` branch
3. Those PRs won't be merged into `main` until the day they are officially released, but they can be tagged with `prerelease` to be copied into either the `beta` (for feature PRs) or `next` (for breaking changes) branch, which will be published immediately upon being pushed to.
4. Patches are merged into main, where they are published immediately.

### Rebasing

Before a PR is copied into the `beta` or `next` branch, the branch is rebased onto `main` (i.e. it rebuilds itself on top of `main`). Note that `main` is not affected by this process.

If the rebase fails, the PR cannot be pre-released until the target branch is manually rebased.

**Comment by aleclarson** [comment]
> By the way, have you decided on the frequency for minor releases? Will it be monthly, every set period, or after a certain number of new features?

I hope to release minor versions once a month, but it's not a strict schedule. I think the automatic beta releases are a fine workaround here.

**Comment by aleclarson** [comment]
GitHub releases for patches are now automatically created 🎉 

Same for pre-releases, but those are created in the [radashi-canary](https://github.com/radashi-org/radashi-canary/releases) repository.
